// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_0QSImEjYFmKxBoKiSwcDgyDN4aD6qAg',
    appId: '1:591993564443:web:2c3eb870666f04e3ccf7be',
    messagingSenderId: '591993564443',
    projectId: 'smartpocketapp-70ce1',
    authDomain: 'smartpocketapp-70ce1.firebaseapp.com',
    storageBucket: 'smartpocketapp-70ce1.firebasestorage.app',
    measurementId: 'G-VRL4DRBR45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBuYHTATCykcnUhleiN57_RG02xPiZONQ',
    appId: '1:591993564443:android:cfd09c8cb24bc432ccf7be',
    messagingSenderId: '591993564443',
    projectId: 'smartpocketapp-70ce1',
    storageBucket: 'smartpocketapp-70ce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_rknMOEL_5fEvm_kZaxAR_JI5whuVEM',
    appId: '1:591993564443:ios:81d99b95d5e94c8eccf7be',
    messagingSenderId: '591993564443',
    projectId: 'smartpocketapp-70ce1',
    storageBucket: 'smartpocketapp-70ce1.firebasestorage.app',
    iosBundleId: 'com.example.smartPocketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ_rknMOEL_5fEvm_kZaxAR_JI5whuVEM',
    appId: '1:591993564443:ios:81d99b95d5e94c8eccf7be',
    messagingSenderId: '591993564443',
    projectId: 'smartpocketapp-70ce1',
    storageBucket: 'smartpocketapp-70ce1.firebasestorage.app',
    iosBundleId: 'com.example.smartPocketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_0QSImEjYFmKxBoKiSwcDgyDN4aD6qAg',
    appId: '1:591993564443:web:79f96769b5923e18ccf7be',
    messagingSenderId: '591993564443',
    projectId: 'smartpocketapp-70ce1',
    authDomain: 'smartpocketapp-70ce1.firebaseapp.com',
    storageBucket: 'smartpocketapp-70ce1.firebasestorage.app',
    measurementId: 'G-95KX4E0G6D',
  );
}
